### ISSUE TITLE
Session recording with TypeWriterReadCloser

### ISSUE THREAD

**Issue by furusiyya** [dutchcoders/sshproxy#2]
I am trying to record session with TypeWriterReadCloser but I am novice yet when golang comes towards interfaces :) , [here](https://gist.github.com/MohammadBilalArif/d5763e4365b1c02a031969406d04611e) you can see how I tried but no success. Scanner consume the reader so the proxy client do not receives any response.  I have also tried to go with [TeeReader](https://golang.org/pkg/io/#TeeReader) but it does not implement Closer method. You can put some stuff how I could record? Thanks in advance :)

**Comment by furusiyya** [comment]
I have solved my issue by studying golang interfaces. Thanks for writing such a useful library :)

**Comment by nl5887** [comment]
Great work!
